// flow-typed signature: 3ed29f97d21f8b8ec708606598d9d0d5
// flow-typed version: <<STUB>>/relay-local-schema_v^0.6.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-local-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-local-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-local-schema/lib/classic/__forks__/createRequestError' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/classic/__forks__/formatRequestErrors' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/classic/index' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/classic/NetworkLayer' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/index' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/modern/createFetch' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/modern/index' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/modern/Network' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-local-schema/lib/classic/__forks__/createRequestError.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/classic/__forks__/createRequestError'>;
}
declare module 'relay-local-schema/lib/classic/__forks__/formatRequestErrors.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/classic/__forks__/formatRequestErrors'>;
}
declare module 'relay-local-schema/lib/classic/index.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/classic/index'>;
}
declare module 'relay-local-schema/lib/classic/NetworkLayer.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/classic/NetworkLayer'>;
}
declare module 'relay-local-schema/lib/index.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/index'>;
}
declare module 'relay-local-schema/lib/modern/createFetch.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/modern/createFetch'>;
}
declare module 'relay-local-schema/lib/modern/index.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/modern/index'>;
}
declare module 'relay-local-schema/lib/modern/Network.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/modern/Network'>;
}
