// flow-typed signature: f94ad4304eb705804b4903915802f482
// flow-typed version: <<STUB>>/todomvc-common_v^1.0.4/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'todomvc-common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'todomvc-common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'todomvc-common/base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'todomvc-common/base.js' {
  declare module.exports: $Exports<'todomvc-common/base'>;
}
