// flow-typed signature: 4c2909644618b7788409d9e100506760
// flow-typed version: <<STUB>>/todomvc-app-css_v^2.1.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'todomvc-app-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'todomvc-app-css' {
  declare module.exports: any;
}
